services:
  backend:
    build: ./backend
    container_name: book-backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: book-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend