AWSTemplateFormatVersion: '2010-09-09'
Description: K3s Worker Server

Resources:
  K8sWorkerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: K8s Worker Security Group
      VpcId: !ImportValue Book-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: K8sWorker-SG

  K8sWorkerEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}'
      KeyName: serversshd
      SubnetId: !ImportValue Book-PublicSubnetId
      SecurityGroupIds:
        - !Ref K8sWorkerSG
      Tags:
        - Key: Name
          Value: K8sWorker

Outputs:
  InstanceId:
    Value: !Ref K8sWorkerEC2
    Export:
      Name: K8sWorker-InstanceId

  PublicIP:
    Value: !GetAtt K8sWorkerEC2.PublicIp
    Export:
      Name: K8sWorker-PublicIp
