apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: jodyys/bookapp-backend:v13
        imagePullPolicy: Always

        ports:
        - containerPort: 5001

        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: bookapp-config
              key: APP_ENV