# -*- coding: utf-8 -*-
"""sample_data_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PwD9AK10eqQSyi0_Vra5pFsieN6lTnl
"""

import pandas as pd
import random
from datetime import datetime, timedelta

df = pd.read_csv('books_clean.csv')

"""## Create sample user interactions and generate reading progress data"""

random.seed(5) #fixed random
users = range(0, 200)
df2 = []

for user in users:
   user = random.randint(1, 100) #random user
   book_id = random.randint(1, 8) #random book
   action = random.choice(["view", "search", "rate"]) #random action
   random_month = random.randint(1, 12) #random month
   timestamp = datetime(2025, random_month, 15, 10, 30) + timedelta(days=random.randint(0, 30), hours=random.randint(0, 23), minutes=random.randint(0, 59)) #random timestamp
   total_pages = df.loc[df["id"] == book_id, "pages"].values[0] #mengambil total buku
   pages_read = random.randint(1, total_pages) #random halaman buku yang sudah dibaca
   completion_rate = round(pages_read / total_pages, 2) #hitung completion rate
   df2.append({
            "user_id": user,
            "book_id": book_id,
            "action": action,
            "timestamp": timestamp.isoformat(),
            "pages_read": pages_read,
            "total_pages": total_pages,
            "completion_rate": completion_rate
        })
user_df = pd.DataFrame(df2)
user_df

"""## Download csv file

### user_interaction
"""

#pilih kolom yang akan diambil
selected_columns = ['user_id', 'book_id', 'action', 'timestamp']
user_interaction_df = user_df[selected_columns]
user_interaction_df

#konversi ke csv
user_interaction_df.to_csv("user_interaction.csv", index=False)

"""### reading_progress"""

#pilih kolom yang akan diambil
selected_columns2 = ['user_id', 'book_id', 'pages_read', 'total_pages',	'completion_rate']
progress_df = user_df[selected_columns2]
progress_df

#konversi ke csv
progress_df.to_csv("reading_progress.csv", index=False)